  // 第21课
  { id: 728, kana: "すきやき", romaji: "sukiyaki", kanji: "すき焼き", accent: "⓪", pos: "名", cn: "日式牛肉火锅", lesson: 21 },
  { id: 729, kana: "こと", romaji: "koto", kanji: "事", accent: "②", pos: "名", cn: "事情，经验", lesson: 21 },
  { id: 730, kana: "けいけん", romaji: "kēken", kanji: "経験", accent: "⓪", pos: "名", cn: "经验，经历", lesson: 21 },
  { id: 731, kana: "かんこく", romaji: "kankoku", kanji: "韓国", accent: "①", pos: "专", cn: "韩国", lesson: 21 },
  { id: 732, kana: "たいわん", romaji: "taiwan", kanji: "台湾", accent: "③", pos: "专", cn: "台湾", lesson: 21 },
  { id: 733, kana: "スイス", romaji: "suisu", kanji: "", accent: "①", pos: "专", cn: "瑞士", lesson: 21 },
  { id: 734, kana: "イタリア", romaji: "itaria", kanji: "", accent: "⓪", pos: "专", cn: "意大利", lesson: 21 },
  { id: 735, kana: "はる", romaji: "haru", kanji: "春", accent: "①", pos: "名", cn: "春天", lesson: 21 },
  { id: 736, kana: "なつ", romaji: "natsu", kanji: "夏", accent: "②", pos: "名", cn: "夏天", lesson: 21 },
  { id: 737, kana: "あき", romaji: "aki", kanji: "秋", accent: "①", pos: "名", cn: "秋天", lesson: 21 },
  { id: 738, kana: "ふゆ", romaji: "fuyu", kanji: "冬", accent: "②", pos: "名", cn: "冬天", lesson: 21 },
  { id: 739, kana: "けが", romaji: "kega", kanji: "怪我", accent: "②", pos: "名", cn: "伤", lesson: 21 },
  { id: 740, kana: "さむい", romaji: "samui", kanji: "寒い", accent: "②", pos: "形1", cn: "寒冷", lesson: 21 },
  { id: 741, kana: "たいへん", romaji: "taihen", kanji: "大変", accent: "⓪", pos: "形2", cn: "严重，费事", lesson: 21 },
  { id: 742, kana: "まっすぐ", romaji: "massugu", kanji: "真っ直ぐ", accent: "③", pos: "副", cn: "一直", lesson: 21 },
  { id: 743, kana: "じむしょ", romaji: "jimusho", kanji: "事務所", accent: "②", pos: "名", cn: "办公室", lesson: 21 },
  { id: 744, kana: "しごと", romaji: "shigoto", kanji: "仕事", accent: "⓪", pos: "名", cn: "工作", lesson: 21 },
  { id: 745, kana: "かいぎ", romaji: "kaigi", kanji: "会議", accent: "①", pos: "名", cn: "会议", lesson: 21 },
  { id: 746, kana: "はなみ", romaji: "hanami", kanji: "花見", accent: "③", pos: "名", cn: "赏花", lesson: 21 },
  { id: 747, kana: "えいが", romaji: "ēga", kanji: "映画", accent: "①", pos: "名", cn: "电影", lesson: 21 },
  { id: 748, kana: "かいしゃ", romaji: "kaisha", kanji: "会社", accent: "⓪", pos: "名", cn: "公司", lesson: 21 },
  { id: 749, kana: "やります", romaji: "yarimasu", kanji: "", accent: "③", pos: "动1", cn: "做", lesson: 21 },
  { id: 750, kana: "あるきます", romaji: "arukimasu", kanji: "歩きます", accent: "③", pos: "动1", cn: "走路", lesson: 21 },
  { id: 751, kana: "みせます", romaji: "misemasu", kanji: "見せます", accent: "③", pos: "动2", cn: "给…看", lesson: 21 },
  { id: 752, kana: "おしえます", romaji: "oshiemasu", kanji: "教えます", accent: "④", pos: "动2", cn: "教", lesson: 21 },
  { id: 753, kana: "ならいます", romaji: "naraimasu", kanji: "習います", accent: "④", pos: "动1", cn: "学习", lesson: 21 },
  { id: 754, kana: "つくります", romaji: "tsukurimasu", kanji: "作ります", accent: "③", pos: "动1", cn: "制作", lesson: 21 },
  { id: 755, kana: "もう", romaji: "mō", kanji: "", accent: "①", pos: "副", cn: "已经", lesson: 21 },
  { id: 756, kana: "まだ", romaji: "mada", kanji: "", accent: "①", pos: "副", cn: "还，尚未", lesson: 21 },
  // 第22课
  { id: 757, kana: "まち", romaji: "machi", kanji: "町", accent: "②", pos: "名", cn: "城镇，街", lesson: 22 },
  { id: 758, kana: "せいかつ", romaji: "sēkatsu", kanji: "生活", accent: "⓪", pos: "名", cn: "生活", lesson: 22 },
  { id: 759, kana: "べんり", romaji: "benri", kanji: "便利", accent: "①", pos: "形2", cn: "方便", lesson: 22 },
  { id: 760, kana: "ふべん", romaji: "fuben", kanji: "不便", accent: "①", pos: "形2", cn: "不便", lesson: 22 },
  { id: 761, kana: "こうつう", romaji: "kōtsū", kanji: "交通", accent: "⓪", pos: "名", cn: "交通", lesson: 22 },
  { id: 762, kana: "きんこう", romaji: "kinkō", kanji: "近郊", accent: "⓪", pos: "名", cn: "近郊", lesson: 22 },
  { id: 763, kana: "まわり", romaji: "mawari", kanji: "周り", accent: "⓪", pos: "名", cn: "周围", lesson: 22 },
  { id: 764, kana: "しずか", romaji: "shizuka", kanji: "静か", accent: "①", pos: "形2", cn: "安静", lesson: 22 },
  { id: 765, kana: "にぎやか", romaji: "nigiyaka", kanji: "賑やか", accent: "②", pos: "形2", cn: "热闹", lesson: 22 },
  { id: 766, kana: "あんぜん", romaji: "anzen", kanji: "安全", accent: "⓪", pos: "形2", cn: "安全", lesson: 22 },
  { id: 767, kana: "きけん", romaji: "kiken", kanji: "危険", accent: "⓪", pos: "形2", cn: "危险", lesson: 22 },
  { id: 768, kana: "ひるま", romaji: "hiruma", kanji: "昼間", accent: "③", pos: "名", cn: "白天", lesson: 22 },
  { id: 769, kana: "よる", romaji: "yoru", kanji: "夜", accent: "①", pos: "名", cn: "夜晚", lesson: 22 },
  { id: 770, kana: "あかるい", romaji: "akarui", kanji: "明るい", accent: "③", pos: "形1", cn: "明亮", lesson: 22 },
  { id: 771, kana: "くらい", romaji: "kurai", kanji: "暗い", accent: "②", pos: "形1", cn: "暗", lesson: 22 },
  { id: 772, kana: "ひろい", romaji: "hiroi", kanji: "広い", accent: "②", pos: "形1", cn: "宽广", lesson: 22 },
  { id: 773, kana: "せまい", romaji: "semai", kanji: "狭い", accent: "②", pos: "形1", cn: "狭窄", lesson: 22 },
  { id: 774, kana: "きれい", romaji: "kirē", kanji: "綺麗", accent: "①", pos: "形2", cn: "干净，漂亮", lesson: 22 },
  { id: 775, kana: "きたない", romaji: "kitanai", kanji: "汚い", accent: "③", pos: "形1", cn: "脏", lesson: 22 },
  { id: 776, kana: "たかい", romaji: "takai", kanji: "高い", accent: "②", pos: "形1", cn: "高，贵", lesson: 22 },
  { id: 777, kana: "ひくい", romaji: "hikui", kanji: "低い", accent: "②", pos: "形1", cn: "低", lesson: 22 },
  { id: 778, kana: "ねだん", romaji: "nedan", kanji: "値段", accent: "⓪", pos: "名", cn: "价格", lesson: 22 },
  { id: 779, kana: "やすい", romaji: "yasui", kanji: "安い", accent: "②", pos: "形1", cn: "便宜", lesson: 22 },
  { id: 780, kana: "すむ", romaji: "sumu", kanji: "住む", accent: "①", pos: "动1", cn: "居住", lesson: 22 },
  { id: 781, kana: "はたらきます", romaji: "hatarakimasu", kanji: "働きます", accent: "④", pos: "动1", cn: "工作", lesson: 22 },
  { id: 782, kana: "とおい", romaji: "tōi", kanji: "遠い", accent: "②", pos: "形1", cn: "远", lesson: 22 },
  { id: 783, kana: "ちかい", romaji: "chikai", kanji: "近い", accent: "②", pos: "形1", cn: "近", lesson: 22 },
  { id: 784, kana: "しんぱい", romaji: "shinpai", kanji: "心配", accent: "⓪", pos: "形2", cn: "担心", lesson: 22 },
  { id: 785, kana: "どう", romaji: "dō", kanji: "", accent: "①", pos: "副", cn: "怎样", lesson: 22 },
  { id: 786, kana: "そんなに", romaji: "sonnani", kanji: "", accent: "⓪", pos: "副", cn: "那么", lesson: 22 },
  { id: 787, kana: "たてもの", romaji: "tatemono", kanji: "建物", accent: "②", pos: "名", cn: "建筑物", lesson: 22 },
  { id: 788, kana: "みせ", romaji: "mise", kanji: "店", accent: "②", pos: "名", cn: "店", lesson: 22 },
  { id: 789, kana: "やすみ", romaji: "yasumi", kanji: "休み", accent: "③", pos: "名", cn: "休息", lesson: 22 },
  { id: 790, kana: "すみやすい", romaji: "sumiyasui", kanji: "住みやすい", accent: "③", pos: "短语", cn: "容易住", lesson: 22 },
  { id: 791, kana: "すみにくい", romaji: "suminikui", kanji: "住みにくい", accent: "③", pos: "短语", cn: "难住", lesson: 22 },
  // 第23课
  { id: 792, kana: "よやく", romaji: "yoyaku", kanji: "予約", accent: "⓪", pos: "名", cn: "预约", lesson: 23 },
  { id: 793, kana: "てがみ", romaji: "tegami", kanji: "手紙", accent: "⓪", pos: "名", cn: "信", lesson: 23 },
  { id: 794, kana: "そうだん", romaji: "sōdan", kanji: "相談", accent: "⓪", pos: "名", cn: "商量", lesson: 23 },
  { id: 795, kana: "れんらく", romaji: "renraku", kanji: "連絡", accent: "⓪", pos: "名", cn: "联系", lesson: 23 },
  { id: 796, kana: "きっぷ", romaji: "kippu", kanji: "切符", accent: "⓪", pos: "名", cn: "票", lesson: 23 },
  { id: 797, kana: "れんしゅう", romaji: "renshū", kanji: "練習", accent: "⓪", pos: "名", cn: "练习", lesson: 23 },
  { id: 798, kana: "しけん", romaji: "shiken", kanji: "試験", accent: "①", pos: "名", cn: "考试", lesson: 23 },
  { id: 799, kana: "しゅくだい", romaji: "shukudai", kanji: "宿題", accent: "⓪", pos: "名", cn: "作业", lesson: 23 },
  { id: 800, kana: "せんぱい", romaji: "senpai", kanji: "先輩", accent: "⓪", pos: "名", cn: "前辈", lesson: 23 },
  { id: 801, kana: "ともだち", romaji: "tomodachi", kanji: "友達", accent: "⓪", pos: "名", cn: "朋友", lesson: 23 },
  { id: 802, kana: "しんゆう", romaji: "shinyū", kanji: "親友", accent: "⓪", pos: "名", cn: "好朋友", lesson: 23 },
  { id: 803, kana: "しゅじゅつ", romaji: "shujutsu", kanji: "手術", accent: "①", pos: "名", cn: "手术", lesson: 23 },
  { id: 804, kana: "せわ", romaji: "sewa", kanji: "世話", accent: "②", pos: "名", cn: "照顾", lesson: 23 },
  { id: 805, kana: "てつだいます", romaji: "tetsudaimasu", kanji: "手伝います", accent: "④", pos: "动1", cn: "帮忙", lesson: 23 },
  { id: 806, kana: "さがします", romaji: "sagashimasu", kanji: "探します", accent: "④", pos: "动1", cn: "寻找", lesson: 23 },
  { id: 807, kana: "かします", romaji: "kashimasu", kanji: "貸します", accent: "③", pos: "动1", cn: "借出", lesson: 23 },
  { id: 808, kana: "かります", romaji: "karimasu", kanji: "借ります", accent: "③", pos: "动2", cn: "借入", lesson: 23 },
  { id: 809, kana: "もらいます", romaji: "moraimasu", kanji: "貰います", accent: "③", pos: "动1", cn: "得到", lesson: 23 },
  { id: 810, kana: "あげます", romaji: "agemasu", kanji: "上げます", accent: "⓪", pos: "动2", cn: "给", lesson: 23 },
  { id: 811, kana: "かけます", romaji: "kakemasu", kanji: "掛けます", accent: "②", pos: "动2", cn: "打(电话)", lesson: 23 },
  { id: 812, kana: "とります", romaji: "torimasu", kanji: "取ります", accent: "③", pos: "动1", cn: "取", lesson: 23 },
  { id: 813, kana: "ひきます", romaji: "hikimasu", kanji: "引きます", accent: "③", pos: "动1", cn: "拉，抽", lesson: 23 },
  { id: 814, kana: "かわります", romaji: "kawarimasu", kanji: "変わります", accent: "④", pos: "动1", cn: "变，改变", lesson: 23 },
  { id: 815, kana: "あんないします", romaji: "annai shimasu", kanji: "案内～", accent: "⑤", pos: "动3", cn: "引导，导游", lesson: 23 },
  { id: 816, kana: "いい", romaji: "ii", kanji: "良い", accent: "①", pos: "形1", cn: "好", lesson: 23 },
  { id: 817, kana: "わるい", romaji: "warui", kanji: "悪い", accent: "②", pos: "形1", cn: "坏", lesson: 23 },
  { id: 818, kana: "はじめて", romaji: "hajimete", kanji: "初めて", accent: "②", pos: "副", cn: "第一次", lesson: 23 },
  { id: 819, kana: "さきに", romaji: "sakini", kanji: "先に", accent: "⓪", pos: "副", cn: "先", lesson: 23 },
  { id: 820, kana: "ぜひ", romaji: "zehi", kanji: "是非", accent: "①", pos: "副", cn: "务必", lesson: 23 },
  { id: 821, kana: "とうきょうえき", romaji: "tōkyō eki", kanji: "東京駅", accent: "⑤", pos: "专", cn: "东京站", lesson: 23 },
  // 第24课
  { id: 822, kana: "ハイキング", romaji: "haikingu", kanji: "", accent: "①", pos: "名", cn: "郊游，远足", lesson: 24 },
  { id: 823, kana: "おわかれ", romaji: "owakare", kanji: "お別れ", accent: "⓪", pos: "名", cn: "分别，分手", lesson: 24 },
  { id: 824, kana: "はなし", romaji: "hanashi", kanji: "話", accent: "③", pos: "名", cn: "说话", lesson: 24 },
  { id: 825, kana: "みおくり", romaji: "miokuri", kanji: "見送り", accent: "⓪", pos: "名", cn: "送行，送别", lesson: 24 },
  { id: 826, kana: "あいだ", romaji: "aida", kanji: "間", accent: "⓪", pos: "名", cn: "时间，期间", lesson: 24 },
  { id: 827, kana: "ほうりつ", romaji: "hōritsu", kanji: "法律", accent: "⓪", pos: "名", cn: "法律", lesson: 24 },
  { id: 828, kana: "おもいます", romaji: "omoimasu", kanji: "思います", accent: "④", pos: "动1", cn: "想，思考", lesson: 24 },
  { id: 829, kana: "いいます", romaji: "iimasu", kanji: "言います", accent: "③", pos: "动1", cn: "说，讲", lesson: 24 },
  { id: 830, kana: "さがします", romaji: "sagashimasu", kanji: "探します", accent: "④", pos: "动1", cn: "找，寻找", lesson: 24 },
  { id: 831, kana: "わらいます", romaji: "waraimasu", kanji: "笑います", accent: "④", pos: "动1", cn: "笑", lesson: 24 },
  { id: 832, kana: "やめます", romaji: "yamemasu", kanji: "", accent: "③", pos: "动2", cn: "戒，停止，放弃", lesson: 24 },
  { id: 833, kana: "きめます", romaji: "kimemasu", kanji: "決めます", accent: "③", pos: "动2", cn: "决定", lesson: 24 },
  { id: 834, kana: "ねぼうします", romaji: "nebō shimasu", kanji: "寝坊～", accent: "⑤", pos: "动3", cn: "睡懒觉", lesson: 24 },
  { id: 835, kana: "がいしゅつします", romaji: "gaishutsu shimasu", kanji: "外出～", accent: "⑥", pos: "动3", cn: "外出，出去", lesson: 24 },
  { id: 836, kana: "けんきゅうします", romaji: "kenkyū shimasu", kanji: "研究～", accent: "⑥", pos: "动3", cn: "研究", lesson: 24 },
  { id: 837, kana: "おかしい", romaji: "okashii", kanji: "", accent: "③", pos: "形1", cn: "可笑，滑稽", lesson: 24 },
  { id: 838, kana: "いっぱい", romaji: "ippai", kanji: "一杯", accent: "⓪", pos: "副", cn: "满", lesson: 24 },
  { id: 839, kana: "すごい", romaji: "sugoi", kanji: "凄い", accent: "②", pos: "副", cn: "惊人的，了不起", lesson: 24 },
  { id: 840, kana: "とうとう", romaji: "tōtō", kanji: "到頭", accent: "①", pos: "副", cn: "终于，终究", lesson: 24 },
  { id: 841, kana: "かならず", romaji: "kanarazu", kanji: "必ず", accent: "⓪", pos: "副", cn: "一定，必定", lesson: 24 },
  { id: 842, kana: "ぜったいに", romaji: "zettai ni", kanji: "絶対に", accent: "⓪", pos: "副", cn: "绝对", lesson: 24 },
  { id: 843, kana: "ば", romaji: "ba", kanji: "馬", accent: "①", pos: "专", cn: "马", lesson: 24 },
  { id: 844, kana: "おげんきで", romaji: "o genki de", kanji: "お元気で", accent: "⓪", pos: "短语", cn: "请多保重", lesson: 24 },
  { id: 845, kana: "おきをつけて", romaji: "o ki o tsukete", kanji: "お気をつけて", accent: "⓪", pos: "短语", cn: "小心点儿", lesson: 24 },
  { id: 846, kana: "さようなら", romaji: "sayōnara", kanji: "", accent: "④", pos: "短语", cn: "再见", lesson: 24 },
  { id: 847, kana: "どうやって", romaji: "dō yatte", kanji: "", accent: "①", pos: "短语", cn: "怎样，如何", lesson: 24 },
  { id: 848, kana: "やくにたちます", romaji: "yaku ni tachimasu", kanji: "役に立ちます", accent: "⑤", pos: "短语", cn: "有用", lesson: 24 },
  { id: 849, kana: "おなかがいっぱいです", romaji: "onaka ga ippai desu", kanji: "", accent: "⓪", pos: "短语", cn: "吃饱，饱", lesson: 24 }
