import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "第 0 阶段 · 环境与工具",
      prefix: "00-setup-and-tooling/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-dev-environment",
        "02-git-and-collaboration",
        "03-gpu-setup-and-cloud",
        "04-apis-and-keys",
        "05-jupyter-notebooks",
        "06-python-environments",
        "07-docker-for-ai",
        "08-editor-setup",
        "09-data-management",
        "10-terminal-and-shell",
        "11-linux-for-ai",
        "12-debugging-and-profiling",
      ],
    },
    {
      text: "第 1 阶段 · 数学基础",
      prefix: "01-math-foundations/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-linear-algebra-intuition",
        "02-vectors-matrices-operations",
        "03-matrix-transformations",
        "04-calculus-for-ml",
        "05-chain-rule-and-autodiff",
        "06-probability-and-distributions",
        "07-bayes-theorem",
        "08-optimization",
        "09-information-theory",
        "10-dimensionality-reduction",
        "11-singular-value-decomposition",
        "12-tensor-operations",
        "13-numerical-stability",
        "14-norms-and-distances",
        "15-statistics-for-ml",
        "16-sampling-methods",
        "17-linear-systems",
        "18-convex-optimization",
        "19-complex-numbers",
        "20-fourier-transform",
        "21-graph-theory",
        "22-stochastic-processes",
      ],
    },
    {
      text: "第 2 阶段 · 机器学习基础",
      prefix: "02-ml-fundamentals/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-what-is-machine-learning",
        "02-linear-regression",
        "03-logistic-regression",
        "04-decision-trees",
        "05-support-vector-machines",
        "06-knn-and-distances",
        "07-unsupervised-learning",
        "08-feature-engineering",
        "09-model-evaluation",
        "10-bias-variance",
        "11-ensemble-methods",
        "12-hyperparameter-tuning",
        "13-ml-pipelines",
        "14-naive-bayes",
        "15-time-series",
        "16-anomaly-detection",
        "17-imbalanced-data",
        "18-feature-selection",
      ],
    },
    {
      text: "第 3 阶段 · 深度学习核心",
      prefix: "03-deep-learning-core/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-the-perceptron",
        "02-multi-layer-networks",
        "03-backpropagation",
        "04-activation-functions",
        "05-loss-functions",
        "06-optimizers",
        "07-regularization",
        "08-weight-initialization",
        "09-learning-rate-schedules",
        "10-mini-framework",
        "11-intro-to-pytorch",
        "12-intro-to-jax",
        "13-debugging-neural-networks",
      ],
    },
    {
      text: "第 4 阶段 · 计算机视觉",
      prefix: "04-computer-vision/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-image-fundamentals",
        "02-convolutions-from-scratch",
        "03-cnns-lenet-to-resnet",
        "04-image-classification",
        "05-transfer-learning",
        "06-object-detection-yolo",
        "07-semantic-segmentation-unet",
        "08-instance-segmentation-mask-rcnn",
        "09-image-generation-gans",
        "10-image-generation-diffusion",
        "11-stable-diffusion",
        "12-video-understanding",
        "13-3d-vision-nerf",
        "14-vision-transformers",
        "15-real-time-edge",
        "16-vision-pipeline-capstone",
        "17-self-supervised-vision",
        "18-open-vocab-clip",
        "19-ocr-document-understanding",
        "20-image-retrieval-metric",
        "21-keypoint-pose",
        "22-3d-gaussian-splatting",
        "23-diffusion-transformers-rectified-flow",
        "24-sam3-open-vocab-segmentation",
        "25-vision-language-models",
        "26-monocular-depth",
        "27-multi-object-tracking",
        "28-world-models-video-diffusion",
      ],
    },
    {
      text: "第 5 阶段 · NLP 基础到进阶",
      prefix: "05-nlp-foundations-to-advanced/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-text-processing",
        "02-bag-of-words-tfidf",
        "03-word-embeddings-word2vec",
        "04-glove-fasttext-subword",
        "05-sentiment-analysis",
        "06-named-entity-recognition",
        "07-pos-tagging-parsing",
        "08-cnns-rnns-for-text",
        "09-sequence-to-sequence",
        "10-attention-mechanism",
        "11-machine-translation",
        "12-text-summarization",
        "13-question-answering",
        "14-information-retrieval-search",
        "15-topic-modeling",
        "16-text-generation-pre-transformer",
        "17-chatbots-rule-to-neural",
        "18-multilingual-nlp",
        "19-subword-tokenization",
        "20-structured-outputs-constrained-decoding",
        "21-nli-textual-entailment",
        "22-embedding-models-deep-dive",
        "23-chunking-strategies-rag",
        "24-coreference-resolution",
        "25-entity-linking",
        "26-relation-extraction-kg",
        "27-llm-evaluation-frameworks",
        "28-long-context-evaluation",
        "29-dialogue-state-tracking",
      ],
    },
    {
      text: "第 6 阶段 · 语音与音频",
      prefix: "06-speech-and-audio/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-audio-fundamentals",
        "02-spectrograms-mel-features",
        "03-audio-classification",
        "04-speech-recognition-asr",
        "05-whisper-architecture-finetuning",
        "06-speaker-recognition-verification",
        "07-text-to-speech",
        "08-voice-cloning-conversion",
        "09-music-generation",
        "10-audio-language-models",
        "11-real-time-audio-processing",
        "12-voice-assistant-pipeline",
        "13-neural-audio-codecs",
        "14-voice-activity-detection-turn-taking",
        "15-streaming-speech-to-speech-moshi-hibiki",
        "16-anti-spoofing-audio-watermarking",
        "17-audio-evaluation-metrics",
      ],
    },
    {
      text: "第 7 阶段 · Transformer 深入",
      prefix: "07-transformers-deep-dive/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-why-transformers",
        "02-self-attention-from-scratch",
        "03-multi-head-attention",
        "04-positional-encoding",
        "05-full-transformer",
        "06-bert-masked-language-modeling",
        "07-gpt-causal-language-modeling",
        "08-t5-bart-encoder-decoder",
        "09-vision-transformers",
        "10-audio-transformers-whisper",
        "11-mixture-of-experts",
        "12-kv-cache-flash-attention",
        "13-scaling-laws",
        "14-build-a-transformer-capstone",
        "15-attention-variants",
        "16-speculative-decoding",
      ],
    },
    {
      text: "第 8 阶段 · 生成式 AI",
      prefix: "08-generative-ai/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-generative-models-taxonomy-history",
        "02-autoencoders-vae",
        "03-gans-generator-discriminator",
        "04-conditional-gans-pix2pix",
        "05-stylegan",
        "06-diffusion-ddpm-from-scratch",
        "07-latent-diffusion-stable-diffusion",
        "08-controlnet-lora-conditioning",
        "09-inpainting-outpainting-editing",
        "10-video-generation",
        "11-audio-generation",
        "12-3d-generation",
        "13-flow-matching-rectified-flows",
        "14-evaluation-fid-clip-score",
        "19-visual-autoregressive-var",
      ],
    },
    {
      text: "第 9 阶段 · 强化学习",
      prefix: "09-reinforcement-learning/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-mdps-states-actions-rewards",
        "02-dynamic-programming",
        "03-monte-carlo-methods",
        "04-q-learning-sarsa",
        "05-dqn",
        "06-policy-gradients-reinforce",
        "07-actor-critic-a2c-a3c",
        "08-ppo",
        "09-reward-modeling-rlhf",
        "10-multi-agent-rl",
        "11-sim-to-real-transfer",
        "12-rl-for-games",
      ],
    },
    {
      text: "第 10 阶段 · 从零构建 LLM",
      prefix: "10-llms-from-scratch/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-tokenizers",
        "02-building-a-tokenizer",
        "03-data-pipelines",
        "04-pre-training-mini-gpt",
        "05-scaling-distributed",
        "06-instruction-tuning-sft",
        "07-rlhf",
        "08-dpo",
        "09-constitutional-ai-self-improvement",
        "10-evaluation",
        "11-quantization",
        "12-inference-optimization",
        "13-building-complete-llm-pipeline",
        "14-open-models-architecture-walkthroughs",
        "15-speculative-decoding-eagle3",
        "16-differential-attention-v2",
        "17-native-sparse-attention",
        "18-multi-token-prediction",
        "19-dualpipe-parallelism",
        "20-deepseek-v3-walkthrough",
        "21-jamba-hybrid-ssm-transformer",
        "22-async-hogwild-inference",
        "25-speculative-decoding",
        "34-gradient-checkpointing",
      ],
    },
    {
      text: "第 11 阶段 · LLM 工程",
      prefix: "11-llm-engineering/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-prompt-engineering",
        "02-few-shot-cot",
        "03-structured-outputs",
        "04-embeddings",
        "05-context-engineering",
        "06-rag",
        "07-advanced-rag",
        "08-fine-tuning-lora",
        "09-function-calling",
        "10-evaluation",
        "11-caching-cost",
        "12-guardrails",
        "13-production-app",
        "14-model-context-protocol",
        "15-prompt-caching",
        "16-langgraph-state-machines",
        "17-agent-framework-tradeoffs",
      ],
    },
    {
      text: "第 12 阶段 · 多模态 AI",
      prefix: "12-multimodal-ai/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-vision-transformer-patch-tokens",
        "02-clip-contrastive-pretraining",
        "03-blip2-qformer-bridge",
        "04-flamingo-gated-cross-attention",
        "05-llava-visual-instruction-tuning",
        "06-any-resolution-patch-n-pack",
        "07-open-weight-vlm-recipes",
        "08-llava-onevision-single-multi-video",
        "09-qwen-vl-family-dynamic-fps",
        "10-internvl3-native-multimodal",
        "11-chameleon-early-fusion-tokens",
        "12-emu3-next-token-for-generation",
        "13-transfusion-autoregressive-diffusion",
        "14-show-o-discrete-diffusion-unified",
        "15-janus-pro-decoupled-encoders",
        "16-mio-any-to-any-streaming",
        "17-video-language-temporal-grounding",
        "18-long-video-million-token",
        "19-audio-language-whisper-to-af3",
        "20-omni-models-thinker-talker",
        "21-embodied-vlas-openvla-pi0-groot",
        "22-document-diagram-understanding",
        "23-colpali-vision-native-rag",
        "24-multimodal-rag-cross-modal",
        "25-multimodal-agents-computer-use",
      ],
    },
    {
      text: "第 13 阶段 · 工具与协议",
      prefix: "13-tools-and-protocols/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-the-tool-interface",
        "02-function-calling-deep-dive",
        "03-parallel-and-streaming-tool-calls",
        "04-structured-output",
        "05-tool-schema-design",
        "06-mcp-fundamentals",
        "07-building-an-mcp-server",
        "08-building-an-mcp-client",
        "09-mcp-transports",
        "10-mcp-resources-and-prompts",
        "11-mcp-sampling",
        "12-mcp-roots-and-elicitation",
        "13-mcp-async-tasks",
        "14-mcp-apps",
        "15-mcp-security-tool-poisoning",
        "16-mcp-security-oauth-2-1",
        "17-mcp-gateways-and-registries",
        "18-mcp-auth-production",
        "19-a2a-protocol",
        "20-opentelemetry-genai",
        "21-llm-routing-layer",
        "22-skills-and-agent-sdks",
        "23-capstone-tool-ecosystem",
      ],
    },
    {
      text: "第 14 阶段 · 智能体工程",
      prefix: "14-agent-engineering/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-the-agent-loop",
        "02-rewoo-plan-and-execute",
        "03-reflexion-verbal-rl",
        "04-tree-of-thoughts-lats",
        "05-self-refine-and-critic",
        "06-tool-use-and-function-calling",
        "07-memory-virtual-context-memgpt",
        "08-memory-blocks-sleep-time-compute",
        "09-hybrid-memory-mem0",
        "10-skill-libraries-voyager",
        "11-planning-htn-and-evolutionary",
        "12-anthropic-workflow-patterns",
        "13-langgraph-stateful-graphs",
        "14-autogen-actor-model",
        "15-crewai-role-based-crews",
        "16-openai-agents-sdk",
        "17-claude-agent-sdk",
        "18-agno-and-mastra-runtimes",
        "19-benchmarks-swebench-gaia",
        "20-benchmarks-webarena-osworld",
        "21-computer-use-agents",
        "22-voice-agents-pipecat-livekit",
        "23-otel-genai-conventions",
        "24-agent-observability-platforms",
        "25-multi-agent-debate",
        "26-failure-modes-agentic",
        "27-prompt-injection-defense",
        "28-orchestration-patterns",
        "29-production-runtimes",
        "30-eval-driven-agent-development",
        "31-agent-workbench-why-models-fail",
        "32-minimal-agent-workbench",
        "33-instructions-as-executable-constraints",
        "34-repo-memory-and-state",
        "35-initialization-scripts",
        "36-scope-contracts",
        "37-runtime-feedback-loops",
        "38-verification-gates",
        "39-reviewer-agent",
        "40-multi-session-handoff",
        "41-workbench-for-real-repos",
        "42-agent-workbench-capstone",
      ],
    },
    {
      text: "第 15 阶段 · 自治系统",
      prefix: "15-autonomous-systems/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-long-horizon-agents",
        "02-star-family-reasoning",
        "03-alphaevolve-evolutionary-coding",
        "04-darwin-godel-machine",
        "05-ai-scientist-v2",
        "06-automated-alignment-research",
        "07-recursive-self-improvement",
        "08-bounded-self-improvement",
        "09-coding-agent-landscape",
        "10-claude-code-permission-modes",
        "11-browser-agents",
        "12-durable-execution",
        "13-cost-governors",
        "14-kill-switches-canaries",
        "15-propose-then-commit",
        "16-checkpoints-rollback",
        "17-constitutional-ai",
        "18-llama-guard",
        "19-anthropic-rsp",
        "20-openai-preparedness-deepmind-fsf",
        "21-metr-external-evaluation",
        "22-cais-caisi-societal-risk",
      ],
    },
    {
      text: "第 16 阶段 · 多智能体与群体",
      prefix: "16-multi-agent-and-swarms/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-why-multi-agent",
        "02-fipa-acl-heritage",
        "03-communication-protocols",
        "04-primitive-model",
        "05-supervisor-orchestrator-pattern",
        "06-hierarchical-architecture",
        "07-society-of-mind-debate",
        "08-role-specialization",
        "09-parallel-swarm-networks",
        "10-group-chat-speaker-selection",
        "11-handoffs-and-routines",
        "12-a2a-protocol",
        "13-shared-memory-blackboard",
        "14-consensus-and-bft",
        "15-voting-debate-topology",
        "16-negotiation-bargaining",
        "17-generative-agents-simulation",
        "18-theory-of-mind-coordination",
        "19-swarm-optimization-pso-aco",
        "20-marl-maddpg-qmix-mappo",
        "21-agent-economies",
        "22-production-scaling-queues-checkpoints",
        "23-failure-modes-mast-groupthink",
        "24-evaluation-coordination-benchmarks",
        "25-case-studies-2026-sota",
      ],
    },
    {
      text: "第 17 阶段 · 基础设施与生产",
      prefix: "17-infrastructure-and-production/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-managed-llm-platforms",
        "02-inference-platform-economics",
        "03-gpu-autoscaling-kubernetes",
        "04-vllm-serving-internals",
        "05-eagle3-speculative-decoding",
        "06-sglang-radixattention",
        "07-tensorrt-llm-blackwell",
        "08-inference-metrics-goodput",
        "09-production-quantization",
        "10-cold-start-mitigation",
        "11-multi-region-kv-locality",
        "12-edge-inference",
        "13-llm-observability",
        "14-prompt-semantic-caching",
        "15-batch-apis",
        "16-model-routing",
        "17-disaggregated-prefill-decode",
        "18-vllm-production-stack-lmcache",
        "19-ai-gateways",
        "20-shadow-canary-progressive",
        "21-ab-testing-llm-features",
        "22-load-testing-llm-apis",
        "23-sre-for-ai",
        "24-chaos-engineering-llm",
        "25-security-secrets-audit",
        "26-compliance-frameworks",
        "27-finops-llms",
        "28-self-hosted-serving-selection",
      ],
    },
    {
      text: "第 18 阶段 · 伦理·安全·对齐",
      prefix: "18-ethics-safety-alignment/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-instruction-following-alignment-signal",
        "02-reward-hacking-goodhart",
        "03-direct-preference-optimization-family",
        "04-sycophancy-rlhf-amplification",
        "05-constitutional-ai-rlaif",
        "06-mesa-optimization-deceptive-alignment",
        "07-sleeper-agents-persistent-deception",
        "08-in-context-scheming-frontier-models",
        "09-alignment-faking",
        "10-ai-control-subversion",
        "11-scalable-oversight-weak-to-strong",
        "12-red-teaming-pair-automated-attacks",
        "13-many-shot-jailbreaking",
        "14-ascii-art-visual-jailbreaks",
        "15-indirect-prompt-injection",
        "16-red-team-tooling-garak-llamaguard-pyrit",
        "17-wmdp-dual-use-evaluation",
        "18-frontier-safety-frameworks-rsp-pf-fsf",
        "19-model-welfare-research",
        "20-bias-representational-harm",
        "21-fairness-criteria-group-individual-counterfactual",
        "22-differential-privacy-for-llms",
        "23-watermarking-synthid-stable-signature-c2pa",
        "24-regulatory-frameworks-eu-us-uk-korea",
        "25-echoleak-cves-for-ai",
        "26-model-system-dataset-cards",
        "27-data-provenance-training-governance",
        "28-alignment-research-ecosystem",
        "29-moderation-systems-openai-perspective-llamaguard",
        "30-dual-use-risk-cyber-bio-chem-nuclear",
      ],
    },
    {
      text: "第 19 阶段 · 结课项目",
      prefix: "19-capstone-projects/",
      collapsible: true,
      sidebarSorter: ["readme", "order", "filename"],
      children: [
        "01-terminal-native-coding-agent",
        "02-rag-over-codebase",
        "03-realtime-voice-assistant",
        "04-multimodal-document-qa",
        "05-autonomous-research-agent",
        "06-devops-troubleshooting-agent",
        "07-end-to-end-fine-tuning-pipeline",
        "08-production-rag-chatbot",
        "09-code-migration-agent",
        "10-multi-agent-software-team",
        "11-llm-observability-dashboard",
        "12-video-understanding-pipeline",
        "13-mcp-server-with-registry",
        "14-speculative-decoding-server",
        "15-constitutional-safety-harness",
        "16-github-issue-to-pr-agent",
        "17-personal-ai-tutor",
        "20-agent-harness-loop-contract",
        "21-tool-registry-schema-validation",
        "22-jsonrpc-stdio-transport",
        "23-function-call-dispatcher",
        "24-plan-execute-control-flow",
        "25-verification-gates-observation-budget",
        "26-sandbox-runner-denylist",
        "27-eval-harness-fixture-tasks",
        "28-observability-otel-traces",
        "29-end-to-end-coding-task-demo",
        "30-bpe-tokenizer-from-scratch",
        "31-tokenized-dataset-sliding-window",
        "32-token-positional-embeddings",
        "33-multihead-self-attention",
        "34-transformer-block",
        "35-gpt-model-assembly",
        "36-training-loop-eval",
        "37-loading-pretrained-weights",
        "38-classifier-finetuning",
        "39-instruction-tuning-sft",
        "40-dpo-from-scratch",
        "41-eval-pipeline",
        "42-large-corpus-downloader",
        "43-hdf5-tokenized-corpus",
        "44-cosine-lr-warmup",
        "45-gradient-clipping-amp",
        "46-gradient-accumulation",
        "47-checkpoint-save-resume",
        "48-distributed-fsdp-ddp",
        "49-lm-eval-harness",
        "50-hypothesis-generator",
        "51-literature-retrieval",
        "52-experiment-runner",
        "53-result-evaluator",
        "54-paper-writer",
        "55-critic-loop",
        "56-iteration-scheduler",
        "57-end-to-end-research-demo",
        "58-vision-encoder-patches",
        "59-vit-transformer",
        "60-projection-layer-modality-align",
        "61-cross-attention-fusion",
        "62-vision-language-pretraining",
        "63-multimodal-eval",
        "64-chunking-strategies-advanced",
        "65-hybrid-retrieval-bm25-dense",
        "66-reranker-cross-encoder",
        "67-query-rewriting-hyde",
        "68-rag-eval-precision-recall",
        "69-end-to-end-rag-system",
        "70-task-spec-format",
        "71-classical-metrics",
        "72-code-exec-metric",
        "73-perplexity-calibration",
        "74-leaderboard-aggregation",
        "75-end-to-end-eval-runner",
        "76-collective-ops-from-scratch",
        "77-data-parallel-ddp",
        "78-zero-parameter-sharding",
        "79-pipeline-parallel",
        "80-checkpoint-sharded-resume",
        "81-end-to-end-distributed-train",
        "82-jailbreak-taxonomy",
        "83-prompt-injection-detector",
        "84-refusal-evaluation",
        "85-content-classifier-integration",
        "86-constitutional-rules-engine",
        "87-end-to-end-safety-gate",
      ],
    },
  ],
});
