import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "后端开发",
      icon: "fa6-solid:code",
      prefix: "后端开发/",
      collapsible: true,
      children: [
        {
          text: "CSharp",
          icon: "fa6-brands:microsoft",
          prefix: "CSharp/",
          collapsible: true,
          children: [
            "",
            "垃圾回收机制",
            "委托",
            {
              text: "IL 中间语言",
              icon: "fa6-solid:microchip",
              prefix: "IL中间语言/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 概述篇",
                  icon: "fa6-solid:book-open",
                  prefix: "01_概述篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 工具链篇",
                  icon: "fa6-solid:wrench",
                  prefix: "02_工具链篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 加载与存储",
                  icon: "fa6-solid:arrow-right-arrow-left",
                  prefix: "03_加载与存储/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 算术与位运算",
                  icon: "fa6-solid:calculator",
                  prefix: "04_算术与位运算/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "05 · 比较与控制流",
                  icon: "fa6-solid:code-branch",
                  prefix: "05_比较与控制流/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "06 · 类型转换",
                  icon: "fa6-solid:right-left",
                  prefix: "06_类型转换/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "07 · 方法调用",
                  icon: "fa6-solid:phone",
                  prefix: "07_方法调用/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "08 · 对象与类型",
                  icon: "fa6-solid:cubes",
                  prefix: "08_对象与类型/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "09 · 异常处理",
                  icon: "fa6-solid:triangle-exclamation",
                  prefix: "09_异常处理/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "10 · 泛型与IL",
                  icon: "fa6-solid:layer-group",
                  prefix: "10_泛型与IL/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "11 · 委托与函数指针",
                  icon: "fa6-solid:link",
                  prefix: "11_委托与函数指针/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "12 · 动态发射",
                  icon: "fa6-solid:rocket",
                  prefix: "12_动态发射/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "13 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "13_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "CLR 深度",
              icon: "fa6-solid:microchip",
              prefix: "CLR深度/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · CLR 基础与类型系统",
                  icon: "fa6-solid:cube",
                  prefix: "01_CLR基础与类型系统/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 对象与类型原理",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_对象与类型原理/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 方法与委托原理",
                  icon: "fa6-solid:code",
                  prefix: "03_方法与委托原理/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 接口与泛型原理",
                  icon: "fa6-solid:puzzle-piece",
                  prefix: "04_接口与泛型原理/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "05 · 内存管理与垃圾回收",
                  icon: "fa6-solid:memory",
                  prefix: "05_内存管理与垃圾回收/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "06 · 异常处理与线程",
                  icon: "fa6-solid:triangle-exclamation",
                  prefix: "06_异常处理与线程/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "07 · 异步编程原理",
                  icon: "fa6-solid:rotate",
                  prefix: "07_异步编程原理/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "08 · 高级类型与模式",
                  icon: "fa6-solid:star",
                  prefix: "08_高级类型与模式/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "09 · 性能与诊断",
                  icon: "fa6-solid:gauge-high",
                  prefix: "09_性能与诊断/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "10 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "10_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "Linq",
              icon: "fa6-solid:filter",
              prefix: "Linq/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:seedling",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 投影与筛选",
                  icon: "fa6-solid:filter",
                  prefix: "02_投影与筛选/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 排序与分组",
                  icon: "fa6-solid:arrow-down-wide-short",
                  prefix: "03_排序与分组/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 聚合与统计",
                  icon: "fa6-solid:calculator",
                  prefix: "04_聚合与统计/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "05 · 集合与连接",
                  icon: "fa6-solid:link",
                  prefix: "05_集合与连接/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "06 · 元素与分区",
                  icon: "fa6-solid:scissors",
                  prefix: "06_元素与分区/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "07 · 生成与转换",
                  icon: "fa6-solid:rotate",
                  prefix: "07_生成与转换/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "08 · 高级操作",
                  icon: "fa6-solid:rocket",
                  prefix: "08_高级操作/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "09 · 性能与陷阱",
                  icon: "fa6-solid:triangle-exclamation",
                  prefix: "09_性能与陷阱/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "10 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "10_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
          ],
        },
        {
          text: "数据库",
          icon: "fa6-solid:database",
          prefix: "数据库/",
          collapsible: true,
          children: [
            "",
            {
              text: "MySQL",
              icon: "fa6-brands:mysql",
              prefix: "MySQL/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:cube",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 进阶篇",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_进阶篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 引擎篇",
                  icon: "fa6-solid:gear",
                  prefix: "03_引擎篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 运维篇",
                  icon: "fa6-solid:wrench",
                  prefix: "04_运维篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "05 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "05_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "PostgreSQL",
              icon: "fa6-solid:elephant",
              prefix: "PostgreSQL/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:cube",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 进阶篇",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_进阶篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 运维篇",
                  icon: "fa6-solid:wrench",
                  prefix: "03_运维篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "04_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "SQL Server",
              icon: "fa6-brands:microsoft",
              prefix: "SQLServer/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:cube",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 进阶篇",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_进阶篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 运维篇",
                  icon: "fa6-solid:wrench",
                  prefix: "03_运维篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "04_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
          ],
        },
        {
          text: ".NET IoT",
          icon: "fa6-solid:microchip",
          prefix: "DotNet_IoT/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · 物联网基础",
              icon: "fa6-solid:globe",
              prefix: "01_物联网基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 硬件接口与 GPIO",
              icon: "fa6-solid:microchip",
              prefix: "02_硬件接口与GPIO/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · 通信协议",
              icon: "fa6-solid:network-wired",
              prefix: "03_通信协议/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 传感器与执行器",
              icon: "fa6-solid:temperature-half",
              prefix: "04_传感器与执行器/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · 边缘计算与网关",
              icon: "fa6-solid:server",
              prefix: "05_边缘计算与网关/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · IoT 平台与云服务",
              icon: "fa6-solid:cloud",
              prefix: "06_IoT平台与云服务/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 安全与认证",
              icon: "fa6-solid:shield-halved",
              prefix: "07_安全与认证/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · 数据管道与分析",
              icon: "fa6-solid:chart-line",
              prefix: "08_数据管道与分析/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级项目实战",
              icon: "fa6-solid:flask",
              prefix: "09_生产级项目实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "10 · 职业发展与面试",
              icon: "fa6-solid:briefcase",
              prefix: "10_职业发展与面试/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "RabbitMQ",
          icon: "fa6-solid:envelope",
          prefix: "RabbitMQ/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · RabbitMQ 基础",
              icon: "fa6-solid:cube",
              prefix: "01_RabbitMQ基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 核心概念与架构",
              icon: "fa6-solid:sitemap",
              prefix: "02_核心概念与架构/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · 交换机与路由",
              icon: "fa6-solid:route",
              prefix: "03_交换机与路由/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 消息可靠性",
              icon: "fa6-solid:shield-halved",
              prefix: "04_消息可靠性/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · 高级特性",
              icon: "fa6-solid:star",
              prefix: "05_高级特性/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · 集群与高可用",
              icon: "fa6-solid:server",
              prefix: "06_集群与高可用/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 性能调优",
              icon: "fa6-solid:gauge-high",
              prefix: "07_性能调优/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · .NET 实战",
              icon: "fa6-brands:microsoft",
              prefix: "08_.NET实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级架构设计",
              icon: "fa6-solid:building",
              prefix: "09_生产级架构设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "10 · 面试题精选",
              icon: "fa6-solid:file-circle-question",
              prefix: "10_面试题精选/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "ABP框架",
          icon: "fa6-brands:microsoft",
          prefix: "ABP框架/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "ASP.NET Core",
          icon: "fa6-brands:microsoft",
          prefix: "ASP.NET_Core/",
          collapsible: true,
          children: [
            "",
            {
              text: "ASP.NET Core 底层原理",
              icon: "fa6-solid:circle-nodes",
              prefix: "AspNetCore底层原理/",
              collapsible: true,
              children: [
                "",
                "00_全链路总览",
                "01_网络层_TCP到Socket",
                "02_Pipelines零拷贝内存模型",
                "03_HTTP协议解析状态机",
                "04_IFeatureCollection接口壁垒",
                "05_HostingApplication交接点",
                "06_中间件管道洋葱圈",
                "07_路由系统DFA匹配",
                "08_认证授权",
                "09_模型绑定",
                "10_Action执行与过滤器",
                "11_输出格式化与响应写回",
                "12_响应返回网卡",
              ],
            },
            {
              text: "提问式学习 ASP.NET Core",
              icon: "fa6-solid:comments",
              prefix: "提问式学习asp.netcore/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "单点登录",
              icon: "fa6-solid:key",
              prefix: "单点登录/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "领域驱动设计",
              icon: "fa6-solid:diagram-project",
              prefix: "领域驱动设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Mok 基础架构设施",
              icon: "fa6-solid:layer-group",
              prefix: "Mok基础架构设施/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "SQL Server 进阶",
              icon: "fa6-solid:database",
              prefix: "SQL Server进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "SQL 知识库",
              icon: "fa6-solid:table",
              prefix: "SQL知识库/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "中间件开发",
              icon: "fa6-solid:gear",
              prefix: "中间件开发/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 中间件基础",
                  icon: "fa6-solid:seedling",
                  prefix: "01_中间件基础/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 常用中间件实战",
                  icon: "fa6-solid:code",
                  prefix: "02_常用中间件实战/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 高级中间件实战",
                  icon: "fa6-solid:rocket",
                  prefix: "03_高级中间件实战/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 中间件设计模式",
                  icon: "fa6-solid:puzzle-piece",
                  prefix: "04_中间件设计模式/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
          ],
        },
        // 算法单独显式声明，保证七个模块顺序固定
        {
          text: "C# 算法知识库",
          icon: "fa6-solid:code",
          prefix: "算法/",
          collapsible: true,
          children: [
            "",
            {
              text: "01. 数据结构基础",
              icon: "fa6-solid:cube",
              prefix: "01_数据结构基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02. 排序算法",
              icon: "fa6-solid:arrow-down-short-wide",
              prefix: "02_排序算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03. 查找算法",
              icon: "fa6-solid:magnifying-glass",
              prefix: "03_查找算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04. 核心算法思想",
              icon: "fa6-solid:lightbulb",
              prefix: "04_核心算法思想/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05. 树与图算法",
              icon: "fa6-solid:diagram-project",
              prefix: "05_树与图算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06. 字符串算法",
              icon: "fa6-solid:font",
              prefix: "06_字符串算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07. 数学算法",
              icon: "fa6-solid:calculator",
              prefix: "07_数学算法/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "Rust",
          icon: "fa6-brands:rust",
          prefix: "Rust/",
          collapsible: true,
          children: [
            "",
            {
              text: "Rust基础",
              icon: "fa6-solid:graduation-cap",
              prefix: "Rust基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "MoCLI · CLI 工具",
              icon: "fa6-solid:terminal",
              prefix: "MoCLI/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Restrel · Web 服务服务器",
              icon: "fa6-solid:server",
              prefix: "Restrel/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "MoNode · 嵌入式",
              icon: "fa6-solid:microchip",
              prefix: "MoNode/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        // 权限设计单独显式声明，保证六个模块顺序固定
        {
          text: "权限系统设计",
          icon: "fa6-solid:shield-halved",
          prefix: "权限设计/",
          collapsible: true,
          children: [
            "",
            {
              text: "01. 权限模型演进",
              icon: "fa6-solid:timeline",
              prefix: "01_权限模型演进/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02. RBAC 深度解析",
              icon: "fa6-solid:id-badge",
              prefix: "02_RBAC深度解析/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03. ABAC 细粒度控制",
              icon: "fa6-solid:filter",
              prefix: "03_ABAC细粒度控制/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04. PBAC 策略引擎",
              icon: "fa6-solid:gavel",
              prefix: "04_PBAC策略引擎/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05. 混合架构落地",
              icon: "fa6-solid:layer-group",
              prefix: "05_混合架构落地/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06. 性能与工程实践",
              icon: "fa6-solid:gauge-high",
              prefix: "06_性能与工程实践/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "Redis",
          icon: "fa6-solid:bolt",
          prefix: "Redis/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · Redis 基础",
              icon: "fa6-solid:cube",
              prefix: "01_Redis基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 数据类型与结构",
              icon: "fa6-solid:layer-group",
              prefix: "02_数据类型与结构/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · 持久化机制",
              icon: "fa6-solid:hard-drive",
              prefix: "03_持久化机制/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 复制与高可用",
              icon: "fa6-solid:server",
              prefix: "04_复制与高可用/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · 集群与分片",
              icon: "fa6-solid:network-wired",
              prefix: "05_集群与分片/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · 内存管理与性能",
              icon: "fa6-solid:gauge-high",
              prefix: "06_内存管理与性能/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 高级特性",
              icon: "fa6-solid:star",
              prefix: "07_高级特性/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · .NET 实战",
              icon: "fa6-brands:microsoft",
              prefix: "08_.NET实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级架构设计",
              icon: "fa6-solid:building",
              prefix: "09_生产级架构设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "10 · 面试题精选",
              icon: "fa6-solid:file-circle-question",
              prefix: "10_面试题精选/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
      ],
    },
    {
      text: "前端开发",
      icon: "fa6-solid:laptop-code",
      prefix: "前端开发/",
      collapsible: true,
      children: [
        "",
        {
          text: "ES6 教程",
          icon: "fa6-solid:code",
          prefix: "ES6教程/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "JavaScript 教程",
          icon: "fa6-brands:js",
          prefix: "JavaScript教程/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "TypeScript 从零实现 axios",
          icon: "fa6-solid:code-branch",
          prefix: "TypeScript 从零实现 axios/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "React 19 教程",
          icon: "fa6-brands:react",
          prefix: "react19教程/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "React 中后台架构知识库",
          icon: "fa6-solid:sitemap",
          prefix: "React中后台架构知识库/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "TailwindCSS",
          icon: "fa6-solid:palette",
          prefix: "TailwindCSS/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "TailwindCSS 知识库",
          icon: "fa6-solid:swatchbook",
          prefix: "TailwindCSS知识库/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "SaaS 实战开发",
          icon: "fa6-solid:building",
          prefix: "Saas实战/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · React 入门与环境搭建",
              icon: "fa6-solid:rocket",
              prefix: "01-React入门与环境搭建/",
              collapsible: true,
              children: [
                "",
                "01-Node与包管理器",
                "02-创建Vite项目",
                "03-安装核心依赖",
                "04-配置Vite与TypeScript",
                "05-shadcn-ui初始化",
                "06-全局样式与字体",
                "07-启动与验证",
              ],
            },
            {
              text: "02 · 项目架构与工程化",
              icon: "fa6-solid:sitemap",
              prefix: "02-项目架构与工程化/",
              collapsible: true,
              children: [
                "",
                "01-目录结构设计",
                "02-工具函数",
                "03-HTTP客户端封装",
                "04-路由系统",
                "05-布局组件",
                "06-状态管理",
                "07-类型定义体系",
              ],
            },
            {
              text: "03 · SSO 单点登录",
              icon: "fa6-solid:key",
              prefix: "03-SSO单点登录/",
              collapsible: true,
              children: [
                "",
                "01-OAuth2与JWT基础",
                "02-登录页面",
                "03-认证API层",
                "04-useAuth-Hook",
                "05-Token管理",
                "06-路由守卫",
                "07-租户选择",
              ],
            },
            {
              text: "04 · 权限中心",
              icon: "fa6-solid:shield-halved",
              prefix: "04-权限中心/",
              collapsible: true,
              children: [
                "",
                "01-RBAC模型与权限树",
                "02-权限API层",
                "03-应用管理",
                "04-权限定义",
                "05-角色管理",
                "06-动态菜单",
                "07-用户角色分配",
                "08-组织架构",
                "09-成员管理",
              ],
            },
            {
              text: "05 · API 网关管理",
              icon: "fa6-solid:network-wired",
              prefix: "05-API网关管理/",
              collapsible: true,
              children: [
                "",
                "01-YARP网关基础",
                "02-网关HTTP客户端",
                "03-集群管理",
                "04-路由管理",
                "05-限流策略",
                "06-网关仪表盘",
              ],
            },
            {
              text: "06 · 文件服务",
              icon: "fa6-solid:file",
              prefix: "06-文件服务/",
              collapsible: true,
              children: [
                "",
                "01-文件服务架构",
                "02-文件API层",
                "03-文件管理器",
                "04-文件上传",
                "05-文件预览",
                "06-配额管理",
                "07-访问控制",
                "08-文件分享",
                "09-回收站",
              ],
            },
            {
              text: "07 · 打印服务",
              icon: "fa6-solid:print",
              prefix: "07-打印服务/",
              collapsible: true,
              children: [
                "",
                "01-模块概览与路由配置",
                "02-API层-模板数据源任务",
                "03-类型系统定义",
                "04-数据源管理页面",
                "05-模板与任务管理页面",
              ],
            },
            {
              text: "08 · 通知中心",
              icon: "fa6-solid:bell",
              prefix: "08-通知中心/",
              collapsible: true,
              children: [
                "",
                "01-实时通信基础",
                "02-SignalR封装",
                "03-通知API层",
                "04-通知铃铛",
                "05-通知列表页",
                "06-模板管理",
                "07-偏好设置",
              ],
            },
            {
              text: "09 · 配置中心",
              icon: "fa6-solid:gears",
              prefix: "09-配置中心/",
              collapsible: true,
              children: [
                "",
                "01-运行时配置概述",
                "02-路由与类型定义",
                "03-配置页面组件",
                "04-加密值交互逻辑",
                "05-Vite代理与最佳实践",
              ],
            },
            {
              text: "10 · 租户运营中心",
              icon: "fa6-solid:building-columns",
              prefix: "10-租户运营中心/",
              collapsible: true,
              children: [
                "",
                "01-SaaS多租户架构",
                "02-运营API层",
                "03-平台概览",
                "04-版本套餐管理",
                "05-租户管理",
                "06-租户详情",
                "07-功能开关",
                "08-Webhook管理",
                "09-MFA管理",
                "10-数据交换",
                "11-工作流",
              ],
            },
            {
              text: "11 · CSS 布局实战",
              icon: "fa6-solid:table-columns",
              prefix: "11-CSS布局实战/",
              collapsible: true,
              children: [
                "",
                "00-布局速查手册",
                "01-登录页居中布局",
                "02-管理后台框架布局",
                "03-数据列表页布局",
                "04-详情页Tab布局",
                "05-表单页布局",
                "06-文件管理器布局",
                "07-仪表盘网格布局",
              ],
            },
          ],
        },
      ],
    },
    {
      text: "架构与设计",
      icon: "fa6-solid:sitemap",
      prefix: "架构与设计/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机学科",
      icon: "fa6-solid:graduation-cap",
      prefix: "计算机学科/",
      collapsible: true,
      children: [
        {
          text: "数字电路",
          icon: "fa6-solid:toggle-on",
          prefix: "数字电路/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "计算机组成原理",
          icon: "fa6-solid:memory",
          prefix: "计算机组成原理/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "汇编语言",
          icon: "fa6-solid:microchip",
          prefix: "汇编语言/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "操作系统",
          icon: "fa6-solid:desktop",
          prefix: "操作系统/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "计算机网络",
          icon: "fa6-solid:network-wired",
          prefix: "计算机网络/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "AI 实践",
      icon: "fa6-solid:robot",
      prefix: "AI实践/",
      collapsible: true,
      children: [
        {
          text: "第一阶段：基础",
          icon: "fa6-solid:seedling",
          prefix: "01_基础阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第二阶段：核心",
          icon: "fa6-solid:fire",
          prefix: "02_核心阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第三阶段：进阶",
          icon: "fa6-solid:bolt",
          prefix: "03_进阶阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第四阶段：架构",
          icon: "fa6-solid:building-columns",
          prefix: "04_架构阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第五阶段：业务落地",
          icon: "fa6-solid:briefcase",
          prefix: "05_业务落地/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "AI 演进史",
          icon: "fa6-solid:clock-rotate-left",
          prefix: "06_AI演进史/",
          collapsible: true,
          children: [
            "",
            {
              text: "符号主义与早期探索",
              icon: "fa6-solid:scroll",
              prefix: "01_符号主义时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "机器学习兴起",
              icon: "fa6-solid:chart-line",
              prefix: "02_机器学习兴起/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "深度学习革命",
              icon: "fa6-solid:brain",
              prefix: "03_深度学习革命/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Transformer 时代",
              icon: "fa6-solid:wand-magic-sparkles",
              prefix: "04_Transformer时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "大语言模型时代",
              icon: "fa6-solid:microchip",
              prefix: "05_大语言模型时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Agent 与未来",
              icon: "fa6-solid:rocket",
              prefix: "06_Agent与未来/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "AI 文档知识库与客服",
          icon: "fa6-solid:book-open-reader",
          prefix: "AI文档库与客服/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "AI 工程师专栏",
          icon: "fa6-solid:user-astronaut",
          prefix: "07_AI工程师专栏/",
          collapsible: true,
          children: [
            {
              text: "岗位画像与能力模型",
              icon: "fa6-solid:map",
              prefix: "01_岗位画像与能力模型/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Prompt 工程深度实践",
              icon: "fa6-solid:pen-fancy",
              prefix: "02_Prompt工程深度实践/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "RAG 系统工程化",
              icon: "fa6-solid:magnifying-glass",
              prefix: "03_RAG系统工程化/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Agent 系统开发",
              icon: "fa6-solid:sitemap",
              prefix: "04_Agent系统开发/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "模型微调与推理优化",
              icon: "fa6-solid:sliders",
              prefix: "05_模型微调与推理优化/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "LLMOps 与生产化",
              icon: "fa6-solid:gears",
              prefix: "06_LLMOps与生产化/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "实战项目与求职",
              icon: "fa6-solid:briefcase",
              prefix: "07_实战项目与求职/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "行业 AI 解决方案",
          icon: "fa6-solid:building",
          prefix: "08_行业AI解决方案/",
          collapsible: true,
          children: [
            {
              text: "金融 AI",
              icon: "fa6-solid:landmark",
              prefix: "01_金融AI/",
              collapsible: true,
              children: [
                {
                  text: "金融行业知识",
                  icon: "fa6-solid:book",
                  prefix: "01_金融行业知识/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "金融 AI 技术",
                  icon: "fa6-solid:microchip",
                  prefix: "02_金融AI技术/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "反欺诈与合规系统",
                  icon: "fa6-solid:shield-halved",
                  prefix: "03_反欺诈与合规系统/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "医疗 AI",
              icon: "fa6-solid:stethoscope",
              prefix: "02_医疗AI/",
              collapsible: true,
              children: [
                {
                  text: "医疗行业知识",
                  icon: "fa6-solid:book",
                  prefix: "01_医疗行业知识/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "医疗 AI 技术",
                  icon: "fa6-solid:microchip",
                  prefix: "02_医疗AI技术/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "智慧诊疗系统",
                  icon: "fa6-solid:hospital",
                  prefix: "03_智慧诊疗系统/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "电商 AI",
              icon: "fa6-solid:cart-shopping",
              prefix: "03_电商AI/",
              collapsible: true,
              children: [
                {
                  text: "电商行业知识",
                  icon: "fa6-solid:book",
                  prefix: "01_电商行业知识/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "电商 AI 技术",
                  icon: "fa6-solid:microchip",
                  prefix: "02_电商AI技术/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "智能供应链系统",
                  icon: "fa6-solid:truck",
                  prefix: "03_智能供应链系统/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
          ],
        },
        {
          text: "Microsoft Agent Framework 实战",
          icon: "fa6-solid:robot",
          prefix: "AgentFramework/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "运维与部署",
      icon: "fa6-solid:rocket",
      prefix: "运维与部署/",
      collapsible: true,
      children: [
        "",
        {
          text: "Docker & Kubernetes",
          icon: "fa6-brands:docker",
          prefix: "Docker_K8s/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · Docker 基础",
              icon: "fa6-brands:docker",
              prefix: "01_Docker基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · Docker 进阶",
              icon: "fa6-solid:layer-group",
              prefix: "02_Docker进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · Docker 生产实战",
              icon: "fa6-solid:flask",
              prefix: "03_Docker生产实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · Kubernetes 基础",
              icon: "fa6-solid:dharmachakra",
              prefix: "04_Kubernetes基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · Kubernetes 进阶",
              icon: "fa6-solid:rocket",
              prefix: "05_Kubernetes进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · Kubernetes 运维",
              icon: "fa6-solid:wrench",
              prefix: "06_Kubernetes运维/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · Kubernetes 生产实战",
              icon: "fa6-solid:building",
              prefix: "07_Kubernetes生产实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · 云原生生态",
              icon: "fa6-solid:cloud",
              prefix: "08_云原生生态/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 面试题精选",
              icon: "fa6-solid:file-circle-question",
              prefix: "09_面试题精选/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
      ],
    },
    {
      text: "Linux",
      icon: "fa6-brands:linux",
      prefix: "Linux/",
      collapsible: true,
      children: [
        "",
        {
          text: "01 · Linux 基础",
          icon: "fa6-solid:cube",
          prefix: "01_Linux基础/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "02 · Linux 进阶",
          icon: "fa6-solid:layer-group",
          prefix: "02_Linux进阶/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "03 · Linux 高级",
          icon: "fa6-solid:star",
          prefix: "03_Linux高级/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "04 · 三剑客",
          icon: "fa6-solid:scissors",
          prefix: "04_三剑客/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "05 · 生产级实战",
          icon: "fa6-solid:flask",
          prefix: "05_生产级实战/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "06 · 内核级",
          icon: "fa6-solid:microchip",
          prefix: "06_内核级/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "07 · Nginx",
          icon: "fa6-solid:server",
          prefix: "07_Nginx/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · Nginx 基础与架构",
              icon: "fa6-solid:cube",
              prefix: "01_Nginx基础与架构/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 核心配置指令",
              icon: "fa6-solid:sliders",
              prefix: "02_核心配置指令/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · HTTP 核心与虚拟主机",
              icon: "fa6-solid:globe",
              prefix: "03_HTTP核心与虚拟主机/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 反向代理与负载均衡",
              icon: "fa6-solid:arrows-split-up-and-left",
              prefix: "04_反向代理与负载均衡/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · SSL/TLS 与 HTTPS",
              icon: "fa6-solid:lock",
              prefix: "05_SSL_TLS与HTTPS/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · 限流与访问控制",
              icon: "fa6-solid:shield-halved",
              prefix: "06_限流与访问控制/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 缓存与性能优化",
              icon: "fa6-solid:gauge-high",
              prefix: "07_缓存与性能优化/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · 高级特性与扩展",
              icon: "fa6-solid:puzzle-piece",
              prefix: "08_高级特性与扩展/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级实战",
              icon: "fa6-solid:flask",
              prefix: "09_生产级实战/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
      ],
    },
    {
      text: "面试题",
      icon: "fa6-solid:file-circle-question",
      prefix: "面试题/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "业务系统",
      icon: "fa6-solid:building",
      prefix: "业务系统/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "语言",
      icon: "fa6-solid:language",
      prefix: "语言/",
      collapsible: true,
      children: [
        {
          text: "英语",
          icon: "fa6-solid:language",
          prefix: "英语/",
          collapsible: true,
          children: [
            {
              text: "语法俱乐部",
              icon: "fa6-solid:book",
              prefix: "语法俱乐部/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "音标有谱",
              icon: "fa6-solid:music",
              prefix: "音标/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Friends 老友记",
              icon: "fa6-solid:tv",
              prefix: "Friends老友记/",
              collapsible: true,
              sidebarSorter: ["readme", "order", "filename"],
              children: [
                "",
                { text: "第一季", icon: "fa6-solid:tv", prefix: "S01/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第二季", icon: "fa6-solid:tv", prefix: "S02/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第三季", icon: "fa6-solid:tv", prefix: "S03/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第四季", icon: "fa6-solid:tv", prefix: "S04/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第五季", icon: "fa6-solid:tv", prefix: "S05/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第六季", icon: "fa6-solid:tv", prefix: "S06/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第七季", icon: "fa6-solid:tv", prefix: "S07/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第八季", icon: "fa6-solid:tv", prefix: "S08/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第九季", icon: "fa6-solid:tv", prefix: "S09/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
                { text: "第十季", icon: "fa6-solid:tv", prefix: "S10/", collapsible: true, sidebarSorter: ["readme", "order", "filename"], children: "structure" },
              ],
            },
          ],
        },
        {
          text: "日语",
          icon: "fa6-solid:book-open",
          prefix: "日语/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
  ],
});
