import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "后端开发",
      icon: "fa6-solid:code",
      prefix: "后端开发/",
      collapsible: true,
      children: [
        {
          text: "CSharp",
          icon: "fa6-brands:microsoft",
          prefix: "CSharp/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "ABP框架",
          icon: "fa6-brands:microsoft",
          prefix: "ABP框架/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "ASP.NET Core",
          icon: "fa6-brands:microsoft",
          prefix: "ASP.NET_Core/",
          collapsible: true,
          children: [
            "",
            {
              text: "ASP.NET Core 底层原理",
              icon: "fa6-solid:circle-nodes",
              prefix: "AspNetCore底层原理/",
              collapsible: true,
              children: [
                "",
                "00_全链路总览",
                "01_网络层_TCP到Socket",
                "02_Pipelines零拷贝内存模型",
                "03_HTTP协议解析状态机",
                "04_IFeatureCollection接口壁垒",
                "05_HostingApplication交接点",
                "06_中间件管道洋葱圈",
                "07_路由系统DFA匹配",
                "08_认证授权",
                "09_模型绑定",
                "10_Action执行与过滤器",
                "11_输出格式化与响应写回",
                "12_响应返回网卡",
              ],
            },
            {
              text: "提问式学习 ASP.NET Core",
              icon: "fa6-solid:comments",
              prefix: "提问式学习asp.netcore/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "单点登录",
              icon: "fa6-solid:key",
              prefix: "单点登录/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "领域驱动设计",
              icon: "fa6-solid:diagram-project",
              prefix: "领域驱动设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Mok 基础架构设施",
              icon: "fa6-solid:layer-group",
              prefix: "Mok基础架构设施/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "SQL Server 进阶",
              icon: "fa6-solid:database",
              prefix: "SQL Server进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "SQL 知识库",
              icon: "fa6-solid:table",
              prefix: "SQL知识库/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        // 算法单独显式声明，保证七个模块顺序固定
        {
          text: "C# 算法知识库",
          icon: "fa6-solid:code",
          prefix: "算法/",
          collapsible: true,
          children: [
            "",
            {
              text: "01. 数据结构基础",
              icon: "fa6-solid:cube",
              prefix: "01_数据结构基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02. 排序算法",
              icon: "fa6-solid:arrow-down-short-wide",
              prefix: "02_排序算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03. 查找算法",
              icon: "fa6-solid:magnifying-glass",
              prefix: "03_查找算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04. 核心算法思想",
              icon: "fa6-solid:lightbulb",
              prefix: "04_核心算法思想/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05. 树与图算法",
              icon: "fa6-solid:diagram-project",
              prefix: "05_树与图算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06. 字符串算法",
              icon: "fa6-solid:font",
              prefix: "06_字符串算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07. 数学算法",
              icon: "fa6-solid:calculator",
              prefix: "07_数学算法/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "Rust",
          icon: "fa6-brands:rust",
          prefix: "Rust/",
          collapsible: true,
          children: [
            "",
            {
              text: "Rust基础",
              icon: "fa6-solid:graduation-cap",
              prefix: "Rust基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "MoCLI · CLI 工具",
              icon: "fa6-solid:terminal",
              prefix: "MoCLI/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Restrel · Web 服务服务器",
              icon: "fa6-solid:server",
              prefix: "Restrel/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "MoNode · 嵌入式",
              icon: "fa6-solid:microchip",
              prefix: "MoNode/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        // 权限设计单独显式声明，保证六个模块顺序固定
        {
          text: "权限系统设计",
          icon: "fa6-solid:shield-halved",
          prefix: "权限设计/",
          collapsible: true,
          children: [
            "",
            {
              text: "01. 权限模型演进",
              icon: "fa6-solid:timeline",
              prefix: "01_权限模型演进/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02. RBAC 深度解析",
              icon: "fa6-solid:id-badge",
              prefix: "02_RBAC深度解析/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03. ABAC 细粒度控制",
              icon: "fa6-solid:filter",
              prefix: "03_ABAC细粒度控制/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04. PBAC 策略引擎",
              icon: "fa6-solid:gavel",
              prefix: "04_PBAC策略引擎/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05. 混合架构落地",
              icon: "fa6-solid:layer-group",
              prefix: "05_混合架构落地/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06. 性能与工程实践",
              icon: "fa6-solid:gauge-high",
              prefix: "06_性能与工程实践/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
      ],
    },
    {
      text: "前端开发",
      icon: "fa6-solid:laptop-code",
      prefix: "前端开发/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "架构与设计",
      icon: "fa6-solid:sitemap",
      prefix: "架构与设计/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机学科",
      icon: "fa6-solid:graduation-cap",
      prefix: "计算机学科/",
      collapsible: true,
      children: [
        {
          text: "计算机网络",
          icon: "fa6-solid:network-wired",
          prefix: "计算机网络/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "汇编语言",
          icon: "fa6-solid:microchip",
          prefix: "汇编语言/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "操作系统",
          icon: "fa6-solid:desktop",
          prefix: "操作系统/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "AI 实践",
      icon: "fa6-solid:robot",
      prefix: "AI实践/",
      collapsible: true,
      children: [
        {
          text: "第一阶段：基础",
          icon: "fa6-solid:seedling",
          prefix: "01_基础阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第二阶段：核心",
          icon: "fa6-solid:fire",
          prefix: "02_核心阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第三阶段：进阶",
          icon: "fa6-solid:bolt",
          prefix: "03_进阶阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第四阶段：架构",
          icon: "fa6-solid:building-columns",
          prefix: "04_架构阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第五阶段：业务落地",
          icon: "fa6-solid:briefcase",
          prefix: "05_业务落地/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "AI 演进史",
          icon: "fa6-solid:clock-rotate-left",
          prefix: "06_AI演进史/",
          collapsible: true,
          children: [
            "",
            {
              text: "符号主义与早期探索",
              icon: "fa6-solid:scroll",
              prefix: "01_符号主义时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "机器学习兴起",
              icon: "fa6-solid:chart-line",
              prefix: "02_机器学习兴起/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "深度学习革命",
              icon: "fa6-solid:brain",
              prefix: "03_深度学习革命/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Transformer 时代",
              icon: "fa6-solid:wand-magic-sparkles",
              prefix: "04_Transformer时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "大语言模型时代",
              icon: "fa6-solid:microchip",
              prefix: "05_大语言模型时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Agent 与未来",
              icon: "fa6-solid:rocket",
              prefix: "06_Agent与未来/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "AI 文档知识库与客服",
          icon: "fa6-solid:book-open-reader",
          prefix: "AI文档库与客服/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "运维与部署",
      icon: "fa6-solid:rocket",
      prefix: "运维与部署/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Linux",
      icon: "fa6-brands:linux",
      prefix: "Linux/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "面试题",
      icon: "fa6-solid:file-circle-question",
      prefix: "面试题/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "业务系统",
      icon: "fa6-solid:building",
      prefix: "业务系统/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "语言",
      icon: "fa6-solid:language",
      prefix: "语言/",
      collapsible: true,
      children: "structure",
    },
  ],
});
