import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "后端开发",
      icon: "fa6-solid:code",
      prefix: "后端开发/",
      collapsible: true,
      children: [
        {
          text: "CSharp",
          icon: "fa6-brands:microsoft",
          prefix: "CSharp/",
          collapsible: true,
          children: [
            "",
            "垃圾回收机制",
            "委托",
            {
              text: "IL 中间语言",
              icon: "fa6-solid:microchip",
              prefix: "IL中间语言/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 概述篇",
                  icon: "fa6-solid:book-open",
                  prefix: "01_概述篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 工具链篇",
                  icon: "fa6-solid:wrench",
                  prefix: "02_工具链篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 加载与存储",
                  icon: "fa6-solid:arrow-right-arrow-left",
                  prefix: "03_加载与存储/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 算术与位运算",
                  icon: "fa6-solid:calculator",
                  prefix: "04_算术与位运算/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "05 · 比较与控制流",
                  icon: "fa6-solid:code-branch",
                  prefix: "05_比较与控制流/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "06 · 类型转换",
                  icon: "fa6-solid:right-left",
                  prefix: "06_类型转换/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "07 · 方法调用",
                  icon: "fa6-solid:phone",
                  prefix: "07_方法调用/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "08 · 对象与类型",
                  icon: "fa6-solid:cubes",
                  prefix: "08_对象与类型/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "09 · 异常处理",
                  icon: "fa6-solid:triangle-exclamation",
                  prefix: "09_异常处理/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "10 · 泛型与IL",
                  icon: "fa6-solid:layer-group",
                  prefix: "10_泛型与IL/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "11 · 委托与函数指针",
                  icon: "fa6-solid:link",
                  prefix: "11_委托与函数指针/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "12 · 动态发射",
                  icon: "fa6-solid:rocket",
                  prefix: "12_动态发射/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "13 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "13_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
          ],
        },
        {
          text: "数据库",
          icon: "fa6-solid:database",
          prefix: "数据库/",
          collapsible: true,
          children: [
            "",
            {
              text: "MySQL",
              icon: "fa6-brands:mysql",
              prefix: "MySQL/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:cube",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 进阶篇",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_进阶篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 引擎篇",
                  icon: "fa6-solid:gear",
                  prefix: "03_引擎篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 运维篇",
                  icon: "fa6-solid:wrench",
                  prefix: "04_运维篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "05 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "05_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "PostgreSQL",
              icon: "fa6-solid:elephant",
              prefix: "PostgreSQL/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:cube",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 进阶篇",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_进阶篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 运维篇",
                  icon: "fa6-solid:wrench",
                  prefix: "03_运维篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "04_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
            {
              text: "SQL Server",
              icon: "fa6-brands:microsoft",
              prefix: "SQLServer/",
              collapsible: true,
              children: [
                "",
                {
                  text: "01 · 基础篇",
                  icon: "fa6-solid:cube",
                  prefix: "01_基础篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "02 · 进阶篇",
                  icon: "fa6-solid:layer-group",
                  prefix: "02_进阶篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "03 · 运维篇",
                  icon: "fa6-solid:wrench",
                  prefix: "03_运维篇/",
                  collapsible: true,
                  children: "structure",
                },
                {
                  text: "04 · 实战篇",
                  icon: "fa6-solid:flask",
                  prefix: "04_实战篇/",
                  collapsible: true,
                  children: "structure",
                },
              ],
            },
          ],
        },
        {
          text: ".NET IoT",
          icon: "fa6-solid:microchip",
          prefix: "DotNet_IoT/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · 物联网基础",
              icon: "fa6-solid:globe",
              prefix: "01_物联网基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 硬件接口与 GPIO",
              icon: "fa6-solid:microchip",
              prefix: "02_硬件接口与GPIO/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · 通信协议",
              icon: "fa6-solid:network-wired",
              prefix: "03_通信协议/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 传感器与执行器",
              icon: "fa6-solid:temperature-half",
              prefix: "04_传感器与执行器/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · 边缘计算与网关",
              icon: "fa6-solid:server",
              prefix: "05_边缘计算与网关/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · IoT 平台与云服务",
              icon: "fa6-solid:cloud",
              prefix: "06_IoT平台与云服务/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 安全与认证",
              icon: "fa6-solid:shield-halved",
              prefix: "07_安全与认证/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · 数据管道与分析",
              icon: "fa6-solid:chart-line",
              prefix: "08_数据管道与分析/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级项目实战",
              icon: "fa6-solid:flask",
              prefix: "09_生产级项目实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "10 · 职业发展与面试",
              icon: "fa6-solid:briefcase",
              prefix: "10_职业发展与面试/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "RabbitMQ",
          icon: "fa6-solid:envelope",
          prefix: "RabbitMQ/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · RabbitMQ 基础",
              icon: "fa6-solid:cube",
              prefix: "01_RabbitMQ基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 核心概念与架构",
              icon: "fa6-solid:sitemap",
              prefix: "02_核心概念与架构/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · 交换机与路由",
              icon: "fa6-solid:route",
              prefix: "03_交换机与路由/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 消息可靠性",
              icon: "fa6-solid:shield-halved",
              prefix: "04_消息可靠性/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · 高级特性",
              icon: "fa6-solid:star",
              prefix: "05_高级特性/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · 集群与高可用",
              icon: "fa6-solid:server",
              prefix: "06_集群与高可用/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 性能调优",
              icon: "fa6-solid:gauge-high",
              prefix: "07_性能调优/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · .NET 实战",
              icon: "fa6-brands:microsoft",
              prefix: "08_.NET实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级架构设计",
              icon: "fa6-solid:building",
              prefix: "09_生产级架构设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "10 · 面试题精选",
              icon: "fa6-solid:file-circle-question",
              prefix: "10_面试题精选/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "ABP框架",
          icon: "fa6-brands:microsoft",
          prefix: "ABP框架/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "ASP.NET Core",
          icon: "fa6-brands:microsoft",
          prefix: "ASP.NET_Core/",
          collapsible: true,
          children: [
            "",
            {
              text: "ASP.NET Core 底层原理",
              icon: "fa6-solid:circle-nodes",
              prefix: "AspNetCore底层原理/",
              collapsible: true,
              children: [
                "",
                "00_全链路总览",
                "01_网络层_TCP到Socket",
                "02_Pipelines零拷贝内存模型",
                "03_HTTP协议解析状态机",
                "04_IFeatureCollection接口壁垒",
                "05_HostingApplication交接点",
                "06_中间件管道洋葱圈",
                "07_路由系统DFA匹配",
                "08_认证授权",
                "09_模型绑定",
                "10_Action执行与过滤器",
                "11_输出格式化与响应写回",
                "12_响应返回网卡",
              ],
            },
            {
              text: "提问式学习 ASP.NET Core",
              icon: "fa6-solid:comments",
              prefix: "提问式学习asp.netcore/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "单点登录",
              icon: "fa6-solid:key",
              prefix: "单点登录/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "领域驱动设计",
              icon: "fa6-solid:diagram-project",
              prefix: "领域驱动设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Mok 基础架构设施",
              icon: "fa6-solid:layer-group",
              prefix: "Mok基础架构设施/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "SQL Server 进阶",
              icon: "fa6-solid:database",
              prefix: "SQL Server进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "SQL 知识库",
              icon: "fa6-solid:table",
              prefix: "SQL知识库/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        // 算法单独显式声明，保证七个模块顺序固定
        {
          text: "C# 算法知识库",
          icon: "fa6-solid:code",
          prefix: "算法/",
          collapsible: true,
          children: [
            "",
            {
              text: "01. 数据结构基础",
              icon: "fa6-solid:cube",
              prefix: "01_数据结构基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02. 排序算法",
              icon: "fa6-solid:arrow-down-short-wide",
              prefix: "02_排序算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03. 查找算法",
              icon: "fa6-solid:magnifying-glass",
              prefix: "03_查找算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04. 核心算法思想",
              icon: "fa6-solid:lightbulb",
              prefix: "04_核心算法思想/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05. 树与图算法",
              icon: "fa6-solid:diagram-project",
              prefix: "05_树与图算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06. 字符串算法",
              icon: "fa6-solid:font",
              prefix: "06_字符串算法/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07. 数学算法",
              icon: "fa6-solid:calculator",
              prefix: "07_数学算法/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "Rust",
          icon: "fa6-brands:rust",
          prefix: "Rust/",
          collapsible: true,
          children: [
            "",
            {
              text: "Rust基础",
              icon: "fa6-solid:graduation-cap",
              prefix: "Rust基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "MoCLI · CLI 工具",
              icon: "fa6-solid:terminal",
              prefix: "MoCLI/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Restrel · Web 服务服务器",
              icon: "fa6-solid:server",
              prefix: "Restrel/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "MoNode · 嵌入式",
              icon: "fa6-solid:microchip",
              prefix: "MoNode/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        // 权限设计单独显式声明，保证六个模块顺序固定
        {
          text: "权限系统设计",
          icon: "fa6-solid:shield-halved",
          prefix: "权限设计/",
          collapsible: true,
          children: [
            "",
            {
              text: "01. 权限模型演进",
              icon: "fa6-solid:timeline",
              prefix: "01_权限模型演进/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02. RBAC 深度解析",
              icon: "fa6-solid:id-badge",
              prefix: "02_RBAC深度解析/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03. ABAC 细粒度控制",
              icon: "fa6-solid:filter",
              prefix: "03_ABAC细粒度控制/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04. PBAC 策略引擎",
              icon: "fa6-solid:gavel",
              prefix: "04_PBAC策略引擎/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05. 混合架构落地",
              icon: "fa6-solid:layer-group",
              prefix: "05_混合架构落地/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06. 性能与工程实践",
              icon: "fa6-solid:gauge-high",
              prefix: "06_性能与工程实践/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "Redis",
          icon: "fa6-solid:bolt",
          prefix: "Redis/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · Redis 基础",
              icon: "fa6-solid:cube",
              prefix: "01_Redis基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · 数据类型与结构",
              icon: "fa6-solid:layer-group",
              prefix: "02_数据类型与结构/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · 持久化机制",
              icon: "fa6-solid:hard-drive",
              prefix: "03_持久化机制/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · 复制与高可用",
              icon: "fa6-solid:server",
              prefix: "04_复制与高可用/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · 集群与分片",
              icon: "fa6-solid:network-wired",
              prefix: "05_集群与分片/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · 内存管理与性能",
              icon: "fa6-solid:gauge-high",
              prefix: "06_内存管理与性能/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · 高级特性",
              icon: "fa6-solid:star",
              prefix: "07_高级特性/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · .NET 实战",
              icon: "fa6-brands:microsoft",
              prefix: "08_.NET实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 生产级架构设计",
              icon: "fa6-solid:building",
              prefix: "09_生产级架构设计/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "10 · 面试题精选",
              icon: "fa6-solid:file-circle-question",
              prefix: "10_面试题精选/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
      ],
    },
    {
      text: "前端开发",
      icon: "fa6-solid:laptop-code",
      prefix: "前端开发/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "架构与设计",
      icon: "fa6-solid:sitemap",
      prefix: "架构与设计/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机学科",
      icon: "fa6-solid:graduation-cap",
      prefix: "计算机学科/",
      collapsible: true,
      children: [
        {
          text: "计算机网络",
          icon: "fa6-solid:network-wired",
          prefix: "计算机网络/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "汇编语言",
          icon: "fa6-solid:microchip",
          prefix: "汇编语言/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "操作系统",
          icon: "fa6-solid:desktop",
          prefix: "操作系统/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "AI 实践",
      icon: "fa6-solid:robot",
      prefix: "AI实践/",
      collapsible: true,
      children: [
        {
          text: "第一阶段：基础",
          icon: "fa6-solid:seedling",
          prefix: "01_基础阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第二阶段：核心",
          icon: "fa6-solid:fire",
          prefix: "02_核心阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第三阶段：进阶",
          icon: "fa6-solid:bolt",
          prefix: "03_进阶阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第四阶段：架构",
          icon: "fa6-solid:building-columns",
          prefix: "04_架构阶段/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "第五阶段：业务落地",
          icon: "fa6-solid:briefcase",
          prefix: "05_业务落地/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "AI 演进史",
          icon: "fa6-solid:clock-rotate-left",
          prefix: "06_AI演进史/",
          collapsible: true,
          children: [
            "",
            {
              text: "符号主义与早期探索",
              icon: "fa6-solid:scroll",
              prefix: "01_符号主义时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "机器学习兴起",
              icon: "fa6-solid:chart-line",
              prefix: "02_机器学习兴起/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "深度学习革命",
              icon: "fa6-solid:brain",
              prefix: "03_深度学习革命/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Transformer 时代",
              icon: "fa6-solid:wand-magic-sparkles",
              prefix: "04_Transformer时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "大语言模型时代",
              icon: "fa6-solid:microchip",
              prefix: "05_大语言模型时代/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "Agent 与未来",
              icon: "fa6-solid:rocket",
              prefix: "06_Agent与未来/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
        {
          text: "AI 文档知识库与客服",
          icon: "fa6-solid:book-open-reader",
          prefix: "AI文档库与客服/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "运维与部署",
      icon: "fa6-solid:rocket",
      prefix: "运维与部署/",
      collapsible: true,
      children: [
        "",
        {
          text: "Docker & Kubernetes",
          icon: "fa6-brands:docker",
          prefix: "Docker_K8s/",
          collapsible: true,
          children: [
            "",
            {
              text: "01 · Docker 基础",
              icon: "fa6-brands:docker",
              prefix: "01_Docker基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "02 · Docker 进阶",
              icon: "fa6-solid:layer-group",
              prefix: "02_Docker进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "03 · Docker 生产实战",
              icon: "fa6-solid:flask",
              prefix: "03_Docker生产实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "04 · Kubernetes 基础",
              icon: "fa6-solid:dharmachakra",
              prefix: "04_Kubernetes基础/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "05 · Kubernetes 进阶",
              icon: "fa6-solid:rocket",
              prefix: "05_Kubernetes进阶/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "06 · Kubernetes 运维",
              icon: "fa6-solid:wrench",
              prefix: "06_Kubernetes运维/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "07 · Kubernetes 生产实战",
              icon: "fa6-solid:building",
              prefix: "07_Kubernetes生产实战/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "08 · 云原生生态",
              icon: "fa6-solid:cloud",
              prefix: "08_云原生生态/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "09 · 面试题精选",
              icon: "fa6-solid:file-circle-question",
              prefix: "09_面试题精选/",
              collapsible: true,
              children: "structure",
            },
          ],
        },
      ],
    },
    {
      text: "Linux",
      icon: "fa6-brands:linux",
      prefix: "Linux/",
      collapsible: true,
      children: [
        "",
        {
          text: "01 · Linux 基础",
          icon: "fa6-solid:cube",
          prefix: "01_Linux基础/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "02 · Linux 进阶",
          icon: "fa6-solid:layer-group",
          prefix: "02_Linux进阶/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "03 · Linux 高级",
          icon: "fa6-solid:star",
          prefix: "03_Linux高级/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "04 · 三剑客",
          icon: "fa6-solid:scissors",
          prefix: "04_三剑客/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "05 · 生产级实战",
          icon: "fa6-solid:flask",
          prefix: "05_生产级实战/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "06 · 内核级",
          icon: "fa6-solid:microchip",
          prefix: "06_内核级/",
          collapsible: true,
          children: "structure",
        },
      ],
    },
    {
      text: "面试题",
      icon: "fa6-solid:file-circle-question",
      prefix: "面试题/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "业务系统",
      icon: "fa6-solid:building",
      prefix: "业务系统/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "语言",
      icon: "fa6-solid:language",
      prefix: "语言/",
      collapsible: true,
      children: "structure",
    },
  ],
});
