name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        # 删除了 with: version: 9
        # 它会自动识别 package.json 中的 "packageManager": "pnpm@10.10.0"

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # VuePress 1.x 建议用 18
          cache: pnpm

      - name: 安装依赖
        run: pnpm install --frozen-lockfile --shamefully-hoist

      - name: 构建文档
        run: |
          pnpm run build
          touch docs/.vuepress/dist/.nojekyll

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
